name: Frends.IMAP.ReadEmail Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.IMAP.ReadEmail/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      env_var_name_1: IMAP_PASSWORD
      workdir: Frends.IMAP.ReadEmail
    secrets:
      env_var_value_1: ${{ secrets.IMAP_PASSWORD }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      