name: Frends.IMAP.ReadEmail Main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.IMAP.ReadEmail/**'
      - 'Frends.IMAP.ReadEmail.Tests/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      env_var_name_1: IMAP_PASSWORD
      workdir: Frends.IMAP.ReadEmail
    secrets:
      env_var_value_1: ${{ secrets.IMAP_PASSWORD }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      